source "https://rubygems.org"

gem "nakiircbot", "~>1.1.0"
gem "nethttputils"
gem "oga"
gem "nakischema"
gem "unicode-blocks", github: "nakilon/unicode-blocks"
gem "nakicommon-aws-upload", github: "nakilon/nakicommon"
gem "nakicommon", github: "nakilon/nakicommon"

gem "maxitest"
gem "webmock"
