---
? - "#velik_bot"
  - lzhesh_zaviduesh_zlishsya
  - zhesh_zaviduesh_zlishsya
: - 1
  - 1690043282
? - "#nekochan_myp"
  - lzhesh_zaviduesh_zlishsya
  - nekochan_myp
: - 3
  - 1690409120
? - "#nekochan_myp"
  - lzhesh_zaviduesh_zlishsya
  - koreanthunder
: - 1
  - 1690144511
? - "#nekochan_myp"
  - lzhesh_zaviduesh_zlishsya
  - dota
: - -1
  - 1690146673
? - "#nekochan_myp"
  - lzhesh_zaviduesh_zlishsya
  - covid4276
: - 0
  - 1690409907
? - "#nekochan_myp"
  - lzhesh_zaviduesh_zlishsya
  - velik_bot
: - 1
  - 1690146874
? - "#nekochan_myp"
  - sha512_ecdsa
  - covid4276
: - 1
  - 1690146913
? - "#nekochan_myp"
  - qomg
  - covid4276
: - 1
  - 1690146928
? - "#nekochan_myp"
  - joyk73
  - covid4276
: - 1
  - 1690146943
? - "#nekochan_myp"
  - dreame8
  - covid4276
: - 1
  - 1690146957
? - "#nekochan_myp"
  - lzhesh_zaviduesh_zlishsya
  - gachimaster_
: - -1
  - 1690147256
? - "#nekochan_myp"
  - lzhesh_zaviduesh_zlishsya
  - julianvd__
: - 1
  - 1690147584
? - "#nekochan_myp"
  - lzhesh_zaviduesh_zlishsya
  - logovod
: - -1
  - 1690148031
? - "#nekochan_myp"
  - covid4276
  - nekochan_myp
: - -1
  - 1690148047
? - "#nekochan_myp"
  - sha512_ecdsa
  - nekochan_myp
: - -1
  - 1690148069
? - "#nekochan_myp"
  - qomg
  - nekochan_myp
: - -1
  - 1690148088
? - "#nekochan_myp"
  - joyk73
  - nekochan_myp
: - -1
  - 1690148101
? - "#nekochan_myp"
  - dreame8
  - nekochan_myp
: - -1
  - 1690148113
? - "#nekochan_myp"
  - meows__
  - nekochan_myp
: - -2
  - 1690416730
? - "#nekochan_myp"
  - meows__
  - covid4276
: - 2
  - 1690411947
? - "#nekochan_myp"
  - logovod
  - '10'
: - 1
  - 1690148148
? - "#nekochan_myp"
  - meows__
  - julianvd__
: - 1
  - 1690148167
? - "#nekochan_myp"
  - covid4276
  - meows__
: - 2
  - 1690411962
? - "#nekochan_myp"
  - lzhesh_zaviduesh_zlishsya
  - meows__
: - -3
  - 1690411863
? - "#nekochan_myp"
  - lzhesh_zaviduesh_zlishsya
  - ud227
: - -1
  - 1690150715
? - "#nekochan_myp"
  - lzhesh_zaviduesh_zlishsya
  - kuznetsov_sexy
: - -1
  - 1690153685
? - "#korolikarasi"
  - lzhesh_zaviduesh_zlishsya
  - korolikarasi
: - 2
  - 1690314885
? - "#korolikarasi"
  - lzhesh_zaviduesh_zlishsya
  - lobsterpizza5k
: - -1
  - 1690506031
? - "#korolikarasi"
  - lzhesh_zaviduesh_zlishsya
  - velik_bot
: - 1
  - 1690238595
? - "#korolikarasi"
  - korolikarasi
  - thapostle
: - 1
  - 1690238648
? - "#korolikarasi"
  - twixfix
  - wartos
: - 1
  - 1690305878
? - "#korolikarasi"
  - wartos
  - twixfix
: - 1
  - 1690305916
? - "#korolikarasi"
  - korolikarasi
  - ''
: - 1
  - 1690305944
? - "#korolikarasi"
  - wartos
  - ''
: - 1
  - 1690305962
? - "#korolikarasi"
  - lobsterpizza5k
  - lzhesh_zaviduesh_zlishsya
: - -3
  - 1690506005
? - "#korolikarasi"
  - lobsterpizza5k
  - thapostle
: - 1
  - 1690307461
? - "#korolikarasi"
  - korolikarasi
  - wartos
: - 2
  - 1690397816
? - "#korolikarasi"
  - lzhesh_zaviduesh_zlishsya
  - wartos
: - 1
  - 1690312499
? - "#korolikarasi"
  - lzhesh_zaviduesh_zlishsya
  - буянов
: - -2
  - 1690504342
? - "#korolikarasi"
  - korolikarasi
  - d3monburn
: - 1
  - 1690314747
? - "#korolikarasi"
  - lobsterpizza5k
  - korolikarasi
: - -3
  - 1690506011
? - "#korolikarasi"
  - korolikarasi
  - lobsterpizza5k
: - -1
  - 1690479658
? - "#korolikarasi"
  - lobsterpizza5k
  - velik_bot
: - -2
  - 1690506042
? - "#korolikarasi"
  - lzhesh_zaviduesh_zlishsya
  - volic96
: - 1
  - 1690327060
? - "#korolikarasi"
  - lobsterpizza5k
  - seienix
: - -1
  - 1690327657
? - "#korolikarasi"
  - seienix
  - lobsterpizza5k
: - 1
  - 1690327712
? - "#korolikarasi"
  - volic96
  - korolikarasi
: - 1
  - 1690327763
? - "#korolikarasi"
  - lobsterpizza5k
  - volic96
: - -1
  - 1690327804
? - "#ta_samaya_lera"
  - lobsterpizza5k
  - b1zzy_official
: - -2
  - 1690507303
? - "#ta_samaya_lera"
  - b1zzy_official
  - lobsterpizza5k
: - -2
  - 1690507256
? - "#ta_samaya_lera"
  - anatolii_evill
  - lobsterpizza5k
: - -1
  - 1690330326
? - "#ta_samaya_lera"
  - xxxxkoks
  - lobsterpizza5k
: - -1
  - 1690330334
? - "#ta_samaya_lera"
  - lobsterpizza5k
  - ta_samaya_lera
: - 0
  - 1690507218
? - "#ta_samaya_lera"
  - lobsterpizza5k
  - "..."
: - 1
  - 1690330421
? - "#ta_samaya_lera"
  - xxxxkoks
  - ta_samaya_lera
: - -1
  - 1690330509
? - "#ta_samaya_lera"
  - xxxxkoks
  - лере
: - -1
  - 1690330527
? - "#ta_samaya_lera"
  - anatolii_evill
  - ta_samaya_lera
: - -1
  - 1690330530
? - "#ta_samaya_lera"
  - afk_lime
  - ta_samaya_lera
: - -1
  - 1690330538
? - "#ta_samaya_lera"
  - b1zzy_official
  - ta_samaya_lera
: - -1
  - 1690330544
? - "#ta_samaya_lera"
  - albert_136
  - ta_samaya_lera
: - -1
  - 1690330549
? - "#ta_samaya_lera"
  - anatolii_evill
  - korolikarasi
: - -1
  - 1690330650
? - "#ta_samaya_lera"
  - xxxxkoks
  - afk_lime
: - 1
  - 1690330684
? - "#ta_samaya_lera"
  - lobsterpizza5k
  - afk_lime
: - -1
  - 1690330719
? - "#ta_samaya_lera"
  - afk_lime
  - lobsterpizza5k
: - -1
  - 1690330732
? - "#ta_samaya_lera"
  - xxxxkoks
  - никитабуянов
: - -1
  - 1690330788
? - "#ta_samaya_lera"
  - xxxxkoks
  - anatolii_evill
: - -1
  - 1690331183
? - "#ta_samaya_lera"
  - xxxxkoks
  - albert_136
: - -1
  - 1690331196
? - "#ta_samaya_lera"
  - lobsterpizza5k
  - korolikarasi
: - -2
  - 1690507180
? - "#korolikarasi"
  - lobsterpizza5k
  - keepitreallz
: - -1
  - 1690384130
? - "#korolikarasi"
  - keepitreallz
  - lobsterpizza5k
: - -2
  - 1690481936
? - "#korolikarasi"
  - volic96
  - lobsterpizza5k
: - -2
  - 1690481661
? - "#korolikarasi"
  - lobsterpizza5k
  - dedkoroed86
: - -1
  - 1690384527
? - "#korolikarasi"
  - lobsterpizza5k
  - riisuka
: - 0
  - 1690506026
? - "#korolikarasi"
  - lobsterpizza5k
  - wartos
: - -1
  - 1690387728
? - "#korolikarasi"
  - wartos
  - lobsterpizza5k
: - -1
  - 1690387765
? - "#korolikarasi"
  - riisuka
  - lobsterpizza5k
: - 1
  - 1690387796
? - "#korolikarasi"
  - lobsterpizza5k
  - лера,
: - -1
  - 1690390041
? - "#korolikarasi"
  - lobsterpizza5k
  - ta_samaya_lera
: - -1
  - 1690391230
? - "#korolikarasi"
  - lobsterpizza5k
  - peer_presure
: - -1
  - 1690391467
? - "#korolikarasi"
  - lobsterpizza5k
  - yuki4q
: - -1
  - 1690393954
? - "#korolikarasi"
  - yuki4q
  - lobsterpizza5k
: - -1
  - 1690394240
? - "#ta_samaya_lera"
  - lobsterpizza5k
  - gredtaf9
: - -1
  - 1690396254
? - "#nekochan_myp"
  - meows__
  - lzhesh_zaviduesh_zlishsya
: - -1
  - 1690411906
? - "#nekochan_myp"
  - covid4276
  - all
: - 1
  - 1690411925
? - "#nekochan_myp"
  - covid4276
  - lzhesh_zaviduesh_zlishsya
: - 1
  - 1690411967
? - "#nekochan_myp"
  - covid4276
  - velik_bot
: - -1
  - 1690411987
? - "#nekochan_myp"
  - meows__
  - remtouk
: - 1
  - 1690411993
? - "#nekochan_myp"
  - meows__
  - velik_bot
: - -1
  - 1690412032
? - "#korolikarasi"
  - twixfix
  - lobsterpizza5k
: - -1
  - 1690415019
? - "#korolikarasi"
  - lobsterpizza5k
  - twixfix
: - -1
  - 1690415033
? - "#ta_samaya_lera"
  - pepebrzyy
  - ta_samaya_lera
: - -1
  - 1690415035
? - "#ta_samaya_lera"
  - lobsterpizza5k
  - pepebrzyy
: - -1
  - 1690415666
? - "#ta_samaya_lera"
  - lobsterpizza5k
  - velik_bot
: - -1
  - 1690415686
? - "#nekochan_myp"
  - nekochan_myp
  - meows__
: - -1
  - 1690416711
? - "#ta_samaya_lera"
  - lobsterpizza5k
  - kill
: - -1
  - 1690417327
? - "#ta_samaya_lera"
  - lobsterpizza5k
  - kill_4_fame
: - -2
  - 1690507171
? - "#korolikarasi"
  - lzhesh_zaviduesh_zlishsya
  - nekochan_myp
: - 1
  - 1690417551
? - "#korolikarasi"
  - korolikarasi
  - nekochan_myp
: - 1
  - 1690417565
? - "#ta_samaya_lera"
  - lobsterpizza5k
  - darlingknight
: - -1
  - 1690422064
? - "#ta_samaya_lera"
  - korolikarasi
  - lobsterpizza5k
: - -1
  - 1690507259
? - "#ta_samaya_lera"
  - etenaris
  - lobsterpizza5k
: - -1
  - 1690507274
? - "#ta_samaya_lera"
  - lobsterpizza5k
  - etenaris
: - -1
  - 1690507294
? - "#ta_samaya_lera"
  - lobsterpizza5k
  - twixfix
: - -1
  - 1690507331
