# https://github.com/ruby/rake/blob/master/doc/rakefile.rdoc

task :default do sh "rake -T" end

directory "logs"
desc "run tests"
task test: %w{ logs } do
  sh "ruby -c main.rb"
  sh "mtest"
end

desc "backup repdb, dynamic.cfg, logs"
task :backup do
  sh "scp velik:_/nakiircbot/examples/velik_bot/prod.repdb.yaml ./bu.repdb.yaml"
  sh "scp velik:_/nakiircbot/examples/velik_bot/dynamic.cfg.yaml ./bu.dynamic.cfg.yaml"
  sh "rsync -vrut velik:_/nakiircbot/examples/velik_bot/logs/txt.* ./vps_logs/"
end
