source "https://rubygems.org"
gem "nakiircbot", "~>0.1.5"

gem "json_pure"
gem "infoboxer"
gem "oga"
gem "nakischema"
gem "video_info"
gem "metainspector"
gem "reddit_bot"
gem "grpc", "<1.42"
gem "google-cloud-pubsub"

if "darwin" == Gem::Platform.local.os
  gem "minitest", github: "Nakilon/minitest", branch: "patch"   # why patch?
  gem "minitest-around"
  gem "webmock", "=3.12.1"

  gem "byebug"
end
