source "https://rubygems.org"
gem "nakiircbot", "~>0.1.5"

gem "json_pure"
gem "infoboxer"
gem "oga"
gem "nakischema"
gem "video_info"
gem "metainspector"
gem "reddit_bot"

gem "google-cloud-pubsub-v1", "<0.6.1"
gem "gapic-common", "<0.4"
gem "grpc", "=1.35.0"   # Alpine docker image nakilonishe/gcloud-with-grpc-gem
gem "google-cloud-pubsub"

if "darwin" == Gem::Platform.local.os
  gem "minitest", github: "Nakilon/minitest", branch: "patch"   # why patch?
  gem "minitest-around"
  gem "webmock", "=3.12.1"

  gem "byebug"
end
